openapi: 3.0.3
info:
  version: 2.0.0
  title: Crossid API
  termsOfService: 'https://crossid.io/tos'
  contact:
    name: Crossid API Team
    email: api-engineering@crossid.io
  license:
    name: Proprietary
    url: 'https://www.crossid.io/lic'
  x-logo:
    url: 'https://www.crossid.io/logo.png'
  description:
    $ref: ./info-description.md
externalDocs:
  description: Find out more about CrossID
  url: 'https://www.crossid.io'
servers:
  - url: https://{tenant}.{region}.crossid.io/api/v1
    variables:
      tenant:
        default: acme
        description: Tenant Identifier
      region:
        defualt: us
        description: The tenant region
    description: Development
tags:
  - name: Secrets
    description: >-
      Secrets are sensitive data that should be encrypted, such secrets can then be used in various places such as _apps_.
      an example could be a remote app that may need to store password for authentication.
x-tagGroups:
  - name: Tenant API
    tags:
      - Resources
      - Schemas
      - Resource Types
      - Jobs
paths:
  # scim schemas
  #
  /api/v1/scim-schemas:
    post:
      $ref: resources/scim_schemas/create_schema.yml
  /api/v1/scim-schemas/{id}:
    get:
      $ref: resources/scim_schemas/get_schema.yml
    put:
      $ref: resources/scim_schemas/replace_schema.yml
  # resource types
  #
  /api/v1/resource-types:
    get:
      $ref: resources/resource_types/list_resource_types.yml
    post:
      $ref: resources/resource_types/create_resource_type.yml
  /api/v1/resource-types/{id}:
    get:
      $ref: resources/resource_types/get_resource_type.yml
    put:
      $ref: resources/resource_types/replace_resource_type.yml
  # job
  #
  /api/v1/jobs/{id}:
    get:
      $ref: resources/jobs/get_job.yml
  # resources
  #
  /api/v1/resources/{appID}/{resourceTypes}:
    get:
      $ref: resources/resources/list_resources_for_type.yml
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://crossid.us.crossid.io/oauth2/auth'
          tokenUrl: 'https://crossid.us.crossid.io/oauth2/token'
          scopes:
            'manage:read:users': read users info
            'write:users': modify or remove users
