name: Spec PR
# This workflow bundles a spec with the respective changes in the PR
# as a Github artifact.

on:
  pull_request:
    paths:
      - 'spec/**'

jobs:
  generate-preview:
    # skip if PR comes from a fork as this job requires a secret
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: Generate Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Bundle
        run: npm run build

      - uses: actions/upload-artifact@v2
        with:
          name: openapi-bundled
          path: openapi.yaml
